### ISSUE TITLE
Request - remove moment from the bundle

### ISSUE THREAD

**Issue by macbem** [TrueLayer/truelayer-client-javascript#24]
moment.js is only used to get a unix timestamp in one place in the codebase. This can be also done via `Date.now` builtin and would save a lot of bundle size.

Right now, moment.js weighs 225 kB, which can be a lot in some applications ([source](https://bundlephobia.com/result?p=moment@2.22.2)) - `truelayer-client` could be 225 kB smaller if you replaced that one moment.js call with `Date.now()`.

**Comment by macbem** [comment]
Overall, lib size could be improved - it doesn't do anything significant (it mostly just constructs requests) and it weighs almost 1 MB. Most *complete* web apps weigh less than that. 

[(source)](https://bundlephobia.com/result?p=truelayer-client@1.0.9)

**Comment by macbem** [comment]
Well, feel free to ignore this issue now - it's been two weeks, so I just removed your lib from my project and I've rewritten it on my own.

**Comment by smontiu** [comment]
@macbem could you create a PR to share your upgrade? I will review it, thanks

**Comment by riccardoio** [comment]
Sorry for the late response.

I am going to close this issue because we don't want remove momentJS at the moment (we are going to use it for new endpoints)

The library should be used only server side, so the bundle size is ok (even if I agree that could be better)

Thank you for raising the issue though. We'll try to improve with the new releases 🙏
